In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score

_PATH_CODING_DIR = os.path.join('..', 'Data', 'Coding_Results')
_PATH_CODING_TABLE_1 = os.path.join(_PATH_CODING_DIR, 'table1_coding.csv')
_PATH_CODING_TABLE_2 = os.path.join(_PATH_CODING_DIR, 'table2_coding.csv')

In [2]:
__author__ = ["Aleksandar Anžel"]
__copyright__ = ""
__credits__ = ["Aleksandar Anžel", "Georges Hattab"]
__license__ = "GNU General Public License v3.0"
__version__ = "1.0.0"
__maintainer__ = "Aleksandar Anžel"
__email__ = "AnzelA@rki.de"
__status__ = "Stable"

# Table 1 --- Agreement Analysis

In [3]:
df_table_1 = pd.read_csv(_PATH_CODING_TABLE_1)
df_table_1

,tool_id,tool_name,pattern,interaction_category,coder1_support,coder2_support
0,1,HyperbolicBrowser,Tree,FocusContext,Full,Full
1,1,HyperbolicBrowser,Tree,MultipleViews,NaN,NaN
2,1,HyperbolicBrowser,Tree,InteractionWithDimensions,NaN,NaN
3,1,HyperbolicBrowser,Tree,DomainSpecificMethods,NaN,NaN
4,2,MoireGraphs,Tree,FocusContext,Full,Full
...,...,...,...,...,...,...
159,40,HoopDiagram,DisconnectedRing,DomainSpecificMethods,NaN,NaN
160,41,EventTunnel,DisconnectedRing,FocusContext,NaN,NaN
161,41,EventTunnel,DisconnectedRing,MultipleViews,NaN,NaN
162,41,EventTunnel,DisconnectedRing,InteractionWithDimensions,NaN,NaN
163,41,EventTunnel,DisconnectedRing,DomainSpecificMethods,Full,Full

In [4]:
dict_label_mapping = {"Full": 2, "Partial": 1, np.nan: 0}

df_table_1["coder1_int"] = df_table_1["coder1_support"].map(dict_label_mapping)
df_table_1["coder2_int"] = df_table_1["coder2_support"].map(dict_label_mapping)

if df_table_1["coder1_int"].isnull().any() or df_table_1["coder2_int"].isnull().any():
    missing_rows = df_table_1[df_table_1["coder1_int"].isnull() | df_table_1["coder2_int"].isnull()]
    raise ValueError(
        "Found unsupported labels in coder1_support/coder2_support.\n"
        f"Problematic rows:\n{missing_rows}"
    )

df_table_1

,tool_id,tool_name,pattern,interaction_category,coder1_support,coder2_support,coder1_int,coder2_int
0,1,HyperbolicBrowser,Tree,FocusContext,Full,Full,2,2
1,1,HyperbolicBrowser,Tree,MultipleViews,NaN,NaN,0,0
2,1,HyperbolicBrowser,Tree,InteractionWithDimensions,NaN,NaN,0,0
3,1,HyperbolicBrowser,Tree,DomainSpecificMethods,NaN,NaN,0,0
4,2,MoireGraphs,Tree,FocusContext,Full,Full,2,2
...,...,...,...,...,...,...,...,...
159,40,HoopDiagram,DisconnectedRing,DomainSpecificMethods,NaN,NaN,0,0
160,41,EventTunnel,DisconnectedRing,FocusContext,NaN,NaN,0,0
161,41,EventTunnel,DisconnectedRing,MultipleViews,NaN,NaN,0,0
162,41,EventTunnel,DisconnectedRing,InteractionWithDimensions,NaN,NaN,0,0
163,41,EventTunnel,DisconnectedRing,DomainSpecificMethods,Full,Full,2,2

In [5]:
kappa_overall = cohen_kappa_score(df_table_1["coder1_int"], df_table_1["coder2_int"])
print(f"Overall Cohen's kappa across all triples: {kappa_overall:.3f}")

Overall Cohen's kappa across all triples: 0.925

In [6]:
# Compute kappa per interaction category
for cat in df_table_1["interaction_category"].unique():
    subset = df_table_1[df_table_1["interaction_category"] == cat]
    if len(subset) < 2:
        continue
    kappa_cat = cohen_kappa_score(subset["coder1_int"], subset["coder2_int"])
    print(
        f"Cohen's kappa for interaction_category='{cat}' "
        f"({len(subset)} triples): {kappa_cat:.3f}"
    )

Cohen's kappa for interaction_category='FocusContext' (41 triples): 1.000
Cohen's kappa for interaction_category='MultipleViews' (41 triples): 0.940
Cohen's kappa for interaction_category='InteractionWithDimensions' (41 triples): 0.947
Cohen's kappa for interaction_category='DomainSpecificMethods' (41 triples): 0.796

# Table 2 --- Agreement Analysis

In [7]:
df_table_2 = pd.read_csv(_PATH_CODING_TABLE_2)
df_table_2

,library_id,library_name,pattern,interaction_category,coder1_support,coder2_support
0,1,Plotly,Tree,Focus+Context,Partial,Partial
1,1,Plotly,Tree,Multiple Views,Partial,Partial
2,1,Plotly,Tree,Interaction with Dimensions,Partial,NaN
3,1,Plotly,Tree,Domain-Specific Methods,NaN,NaN
4,1,Plotly,Star,Focus+Context,Full,Full
...,...,...,...,...,...,...
191,7,amCharts,Connected Ring,Domain-Specific Methods,NaN,NaN
192,7,amCharts,Disconnected Ring,Focus+Context,NaN,NaN
193,7,amCharts,Disconnected Ring,Multiple Views,NaN,NaN
194,7,amCharts,Disconnected Ring,Interaction with Dimensions,NaN,NaN
195,7,amCharts,Disconnected Ring,Domain-Specific Methods,NaN,NaN

In [8]:
dict_label_mapping = {"Full": 2, "Partial": 1, np.nan: 0}

df_table_2["coder1_int"] = df_table_2["coder1_support"].map(dict_label_mapping)
df_table_2["coder2_int"] = df_table_2["coder2_support"].map(dict_label_mapping)

if df_table_2["coder1_int"].isnull().any() or df_table_2["coder2_int"].isnull().any():
    missing_rows = df_table_2[df_table_2["coder1_int"].isnull() | df_table_2["coder2_int"].isnull()]
    raise ValueError(
        "Found unsupported labels in coder1_support/coder2_support.\n"
        f"Problematic rows:\n{missing_rows}"
    )

df_table_2

,library_id,library_name,pattern,interaction_category,coder1_support,coder2_support,coder1_int,coder2_int
0,1,Plotly,Tree,Focus+Context,Partial,Partial,1,1
1,1,Plotly,Tree,Multiple Views,Partial,Partial,1,1
2,1,Plotly,Tree,Interaction with Dimensions,Partial,NaN,1,0
3,1,Plotly,Tree,Domain-Specific Methods,NaN,NaN,0,0
4,1,Plotly,Star,Focus+Context,Full,Full,2,2
...,...,...,...,...,...,...,...,...
191,7,amCharts,Connected Ring,Domain-Specific Methods,NaN,NaN,0,0
192,7,amCharts,Disconnected Ring,Focus+Context,NaN,NaN,0,0
193,7,amCharts,Disconnected Ring,Multiple Views,NaN,NaN,0,0
194,7,amCharts,Disconnected Ring,Interaction with Dimensions,NaN,NaN,0,0
195,7,amCharts,Disconnected Ring,Domain-Specific Methods,NaN,NaN,0,0

In [9]:
kappa_overall = cohen_kappa_score(df_table_2["coder1_int"], df_table_2["coder2_int"])
print(f"Overall Cohen's kappa across all triples: {kappa_overall:.3f}")

Overall Cohen's kappa across all triples: 0.882

In [10]:
# Compute kappa per interaction category
for cat in df_table_2["interaction_category"].unique():
    subset = df_table_2[df_table_2["interaction_category"] == cat]
    if len(subset) < 2:
        continue
    kappa_cat = cohen_kappa_score(subset["coder1_int"], subset["coder2_int"])
    print(
        f"Cohen's kappa for interaction_category='{cat}' "
        f"({len(subset)} triples): {kappa_cat:.3f}"
    )

Cohen's kappa for interaction_category='Focus+Context' (49 triples): 0.899
Cohen's kappa for interaction_category='Multiple Views' (49 triples): 0.846
Cohen's kappa for interaction_category='Interaction with Dimensions' (49 triples): 0.818
Cohen's kappa for interaction_category='Domain-Specific Methods' (49 triples): nan

/home/alexein-personal/miniconda3/envs/radial_interactive_env/lib/python3.14t/site-packages/sklearn/metrics/_classification.py:614: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
/home/alexein-personal/miniconda3/envs/radial_interactive_env/lib/python3.14t/site-packages/sklearn/utils/_param_validation.py:218: UndefinedMetricWarning: `y1`, `y2` and `labels` have only one label in common. `cohen_kappa_score` is undefined and set to the value defined by the the `replace_undefined_by` param, which is set to nan.
  return func(*args, **kwargs)